FROM ghcr.io/sloretz/ros:humble-desktop

SHELL ["/bin/bash", "-c"]

# Instalar dependencias necesarias para PX4 y ROS 2
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    git \
    wget \
    curl \
    libxml2-utils \
    libxslt1-dev \
    socat \
    net-tools \
    iputils-ping && \
    rm -rf /var/lib/apt/lists/*

# Crear el workspace
RUN mkdir -p /root/ros2_ws/src

# Clonar los repositorios
WORKDIR /root/ros2_ws
RUN git clone -b v2.4.2 https://github.com/eProsima/Micro-XRCE-DDS-Agent.git src/Micro-XRCE-DDS-Agent && \
    git clone https://github.com/PX4/px4_msgs.git src/px4_msgs && \
    git clone https://github.com/PX4/px4_ros_com.git src/px4_ros_com

# Clonar PX4 y ejecutar script de dependencias desde su propia ruta
WORKDIR /root
RUN git clone --recursive https://github.com/PX4/PX4-Autopilot.git
RUN ./PX4-Autopilot/Tools/setup/ubuntu.sh --no-nuttx 

# Compilar el workspace ROS 2
WORKDIR /root/ros2_ws
RUN source /opt/ros/humble/setup.bash && colcon build

# Agregar entornos ROS al bash
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc && \
    echo "source /root/ros2_ws/install/setup.bash" >> ~/.bashrc

# Directorio por defecto y terminal interactiva
WORKDIR /root
CMD ["bash"]


